#!/usr/bin/env bash
#!----------------------------------------------------------------------------!
#!                                                                            !
#! Yexpert : (your) Système Expert sous Mumps GT.M et GNU/Linux               !
#! Copyright (C) 2001-2015 by Hamid LOUAKED (HL).                             !
#!                                                                            !
#!----------------------------------------------------------------------------!

# script init pour Yexpert-JS

# Debian
### BEGIN INIT INFO
# Provides:          y-instanceyexpert-js
# Required-Start:    $remote_fs $syslog $y-instanceyexpert
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Lancer Yexpert-JS pour Yexpert au moment du démarrage
# Description:       Services Starts/Stops Yexpert-JS pour Yexpert.
### END INIT INFO

# Assurez-vous que nous sommes en root
if [[ $EUID -ne 0 ]]; then
    echo "Ce script doit être exécuté en tant que root" 1>&2
    exit 1
fi

# Variables d'environnement
# Ce chemin sera remplacé par le $basedir correspondant à l'instance Yexpert
# qui sera créée. Ce script devra avoir codé "en dur"
source /home/y-instance/config/env
export PATH=$PATH:/usr/local/bin

# Démarrer les services yexpert-...-srv
start() {
    echo "Lancer le serveur yexpert-js-srv"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/config/env && nvm use $nodever && daemon --name yexpert-js-srv -O $basedir/log/yexpert-js-srvOut.log -E $basedir/log/yexpert-js-srvErr.log --chdir $basedir/yexpert-js node $basedir/yexpert-js/yexpert-js-srv.js Yrelay-Config"

    echo "Lancer le serveur yexpert-term-srv"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/config/env && nvm use $nodever && cd $basedir/yexpert-js && daemon --name yexpert-term-srv -O $basedir/log/yexpert-term-srvOut.log -E $basedir/log/yexpert-term-srvErr.log --chdir $basedir/yexpert-js node $basedir/yexpert-js/yexpert-term-srv.js"

    echo "Lancer le serveur yexpert-rpc-srv"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/config/env && nvm use $nodever && daemon --name yexpert-rpc-srv -O $basedir/log/yexpert-rpc-srvOut.log -E $basedir/log/yexpert-rpc-srvErr.log --chdir $basedir/yexpert-js node $basedir/yexpert-js/node_modules/yexpert-rpc/example/yexpert-rpc-srv.js"

}

# Stopper les services yexpert-...-srv
stop() {
    echo "Arrêter le serveur yexpert-js-srv"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/config/env && nvm use $nodever && daemon --name yexpert-js-srv --stop"

    echo "Arrêter le serveur yexpert-term-srv"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/config/env && nvm use $nodever && daemon --name yexpert-term-srv --stop"

    echo "Arrêter le serveur yexpert-rpc-srv"
    su $instance -c "source $basedir/.nvm/nvm.sh && source $basedir/config/env && nvm use $nodever && daemon --name yexpert-rpc-srv --stop"

}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 5
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
